### ISSUE TITLE
Commas inside individual CSV cells are not being handled

### ISSUE THREAD

**Issue by m-spyratos** [alfredkam/bigData#6]
This issue is about the `csv-to-json` module.

When a CSV cell has a value which includes a comma, it wraps this value inside double quotes to avoid the comma from being mistaken for a delimiter. The module does not take this under consideration and the resulted object is broken.

CSV with commas inside cells:

    Account_Name,Last_Activity,Type
    DDL Group,9/27/2011,Integrator
    "Group, Inc.",8/27/2013,Merged

Will produce the following object:

    [
        {
            Account_Name: 'DDL Group',
            Last_Activity: '9/27/2011',
            Type: 'Integrator'
        },
        {
            Account_Name: '"Group',
            Last_Activity: ' Inc."',
            Type: '8/27/2013'
        }
    ]

**Comment by alfredkam** [comment]
fixed under commit https://github.com/alfredkam/bigData/commit/3f40debaf2b35817b66b8a09a19bd63b2d03360c & published @0.1.2
